// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvoGzShUZz_JqoEoO-nkT-4S14UWxObaM',
    appId: '1:648969960683:web:b8bda5fe76753a4aad92ae',
    messagingSenderId: '648969960683',
    projectId: 'qrder-7e07b',
    authDomain: 'qrder-7e07b.firebaseapp.com',
    storageBucket: 'qrder-7e07b.firebasestorage.app',
    measurementId: 'G-JFTZK9QL7B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB87nCxELawRibB4ho0CmXQz0yT5wU-Kwo',
    appId: '1:648969960683:android:78b71594cb2660a6ad92ae',
    messagingSenderId: '648969960683',
    projectId: 'qrder-7e07b',
    storageBucket: 'qrder-7e07b.firebasestorage.app',
  );
}
